// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go

// Package mock_ports is a generated GoMock package.
package mock_ports

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	tictactoe_battle "github.com/swallowarc/tictactoe-battle-proto/pkg/tictactoe_battle"
	battle "github.com/swallowarc/tictactoe_battle_backend/internal/domains/battle"
	room "github.com/swallowarc/tictactoe_battle_backend/internal/domains/room"
)

// MockLoginRepository is a mock of LoginRepository interface.
type MockLoginRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLoginRepositoryMockRecorder
}

// MockLoginRepositoryMockRecorder is the mock recorder for MockLoginRepository.
type MockLoginRepositoryMockRecorder struct {
	mock *MockLoginRepository
}

// NewMockLoginRepository creates a new mock instance.
func NewMockLoginRepository(ctrl *gomock.Controller) *MockLoginRepository {
	mock := &MockLoginRepository{ctrl: ctrl}
	mock.recorder = &MockLoginRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginRepository) EXPECT() *MockLoginRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockLoginRepository) FindByID(ctx context.Context, loginID string) (*tictactoe_battle.Login, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, loginID)
	ret0, _ := ret[0].(*tictactoe_battle.Login)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockLoginRepositoryMockRecorder) FindByID(ctx, loginID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockLoginRepository)(nil).FindByID), ctx, loginID)
}

// Logout mocks base method.
func (m *MockLoginRepository) Logout(ctx context.Context, loginID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, loginID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockLoginRepositoryMockRecorder) Logout(ctx, loginID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockLoginRepository)(nil).Logout), ctx, loginID)
}

// NewLogin mocks base method.
func (m *MockLoginRepository) NewLogin(ctx context.Context, loginID string) (*tictactoe_battle.Login, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewLogin", ctx, loginID)
	ret0, _ := ret[0].(*tictactoe_battle.Login)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewLogin indicates an expected call of NewLogin.
func (mr *MockLoginRepositoryMockRecorder) NewLogin(ctx, loginID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewLogin", reflect.TypeOf((*MockLoginRepository)(nil).NewLogin), ctx, loginID)
}

// ReLogin mocks base method.
func (m *MockLoginRepository) ReLogin(ctx context.Context, login *tictactoe_battle.Login) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReLogin", ctx, login)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReLogin indicates an expected call of ReLogin.
func (mr *MockLoginRepositoryMockRecorder) ReLogin(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReLogin", reflect.TypeOf((*MockLoginRepository)(nil).ReLogin), ctx, login)
}

// MockBattleRepository is a mock of BattleRepository interface.
type MockBattleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBattleRepositoryMockRecorder
}

// MockBattleRepositoryMockRecorder is the mock recorder for MockBattleRepository.
type MockBattleRepositoryMockRecorder struct {
	mock *MockBattleRepository
}

// NewMockBattleRepository creates a new mock instance.
func NewMockBattleRepository(ctrl *gomock.Controller) *MockBattleRepository {
	mock := &MockBattleRepository{ctrl: ctrl}
	mock.recorder = &MockBattleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBattleRepository) EXPECT() *MockBattleRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBattleRepository) Create(ctx context.Context, battle *battle.Battle) (room.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, battle)
	ret0, _ := ret[0].(room.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBattleRepositoryMockRecorder) Create(ctx, battle interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBattleRepository)(nil).Create), ctx, battle)
}

// Delete mocks base method.
func (m *MockBattleRepository) Delete(ctx context.Context, roomID room.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBattleRepositoryMockRecorder) Delete(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBattleRepository)(nil).Delete), ctx, roomID)
}

// Enter mocks base method.
func (m *MockBattleRepository) Enter(ctx context.Context, roomID room.ID, loginID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enter", ctx, roomID, loginID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enter indicates an expected call of Enter.
func (mr *MockBattleRepositoryMockRecorder) Enter(ctx, roomID, loginID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enter", reflect.TypeOf((*MockBattleRepository)(nil).Enter), ctx, roomID, loginID)
}

// IsExistsInRoom mocks base method.
func (m *MockBattleRepository) IsExistsInRoom(ctx context.Context, roomID room.ID, loginID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExistsInRoom", ctx, roomID, loginID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsExistsInRoom indicates an expected call of IsExistsInRoom.
func (mr *MockBattleRepositoryMockRecorder) IsExistsInRoom(ctx, roomID, loginID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExistsInRoom", reflect.TypeOf((*MockBattleRepository)(nil).IsExistsInRoom), ctx, roomID, loginID)
}

// Leave mocks base method.
func (m *MockBattleRepository) Leave(ctx context.Context, roomID room.ID, loginID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leave", ctx, roomID, loginID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Leave indicates an expected call of Leave.
func (mr *MockBattleRepositoryMockRecorder) Leave(ctx, roomID, loginID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leave", reflect.TypeOf((*MockBattleRepository)(nil).Leave), ctx, roomID, loginID)
}

// ListMembers mocks base method.
func (m *MockBattleRepository) ListMembers(ctx context.Context, roomID room.ID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, roomID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockBattleRepositoryMockRecorder) ListMembers(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockBattleRepository)(nil).ListMembers), ctx, roomID)
}

// ReadStream mocks base method.
func (m *MockBattleRepository) ReadStream(ctx context.Context, roomID room.ID, messageID string) (string, *battle.Battle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadStream", ctx, roomID, messageID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*battle.Battle)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadStream indicates an expected call of ReadStream.
func (mr *MockBattleRepositoryMockRecorder) ReadStream(ctx, roomID, messageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadStream", reflect.TypeOf((*MockBattleRepository)(nil).ReadStream), ctx, roomID, messageID)
}

// ReadStreamLatest mocks base method.
func (m *MockBattleRepository) ReadStreamLatest(ctx context.Context, roomID room.ID) (string, *battle.Battle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadStreamLatest", ctx, roomID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*battle.Battle)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadStreamLatest indicates an expected call of ReadStreamLatest.
func (mr *MockBattleRepositoryMockRecorder) ReadStreamLatest(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadStreamLatest", reflect.TypeOf((*MockBattleRepository)(nil).ReadStreamLatest), ctx, roomID)
}

// Update mocks base method.
func (m *MockBattleRepository) Update(ctx context.Context, battle *battle.Battle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, battle)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBattleRepositoryMockRecorder) Update(ctx, battle interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBattleRepository)(nil).Update), ctx, battle)
}
